services:
  - type: web
    name: 365solutions-system
    runtime: node
    env: node
    plan: free
    buildCommand: npm install --only=production
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000